# Generated by Django 4.2.5 on 2023-09-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bands',
            new_name='Band',
        ),
    ]
